config/routes.rb
Rails.application.routes.draw do

  get 'rooms/index'
  get 'users/show'
  devise_for :users
  get 'rooms/own'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
  resources :rooms do
    collection do
      post 'search'
    end
  end
  resources :reservations
  post 'reservations/confirm'
  get 'reservations/index'
  
  resources :users
  get 'users/index'
  get 'users/profile'
  
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :room
  
  with_options presence: true do
    validates :check_in
    validates :check_out
    validates :people, numericality: { only_integer: true, greater_than: 0 }
  end
  validate :in_out_check
  
  def in_out_check
    unless check_in == nil || check_out ==nil
    errors.add(:check_out, "はチェックインより後の日付を選択してください") unless
    self.check_in < self.check_out
    end
  end
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :reservations, dependent: :destroy
  has_one_attached :image
    
  with_options presence: true do
    validates :name
    validates :introduction
    validates :price
    validates :address
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_one_attached :avatar
  has_many :rooms, dependent: :destroy
  has_many :reservations, dependent: :destroy
  
  validates :name, presence: true
  validates :avatar, blob: { content_type: ['image/png', 'image/jpg', 'image/jpeg']}
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: %i(avatar))
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  protect_from_forgery
  before_action :authenticate_user!

  def index
    @reservations = current_user.reservations
  end

  def confirm
    @reservation = Reservation.new(reservation_params)
    @room = Room.find_by(params[:room_id])
    if @reservation.invalid?
      render template: "rooms/show"
      return
    end
  end
  
  def create
    @reservation = Reservation.new(reservation_params)
    if @reservation.save
      flash[:notice] = "予約が完了しました"
      redirect_to reservations_path
    else
      flash[:alert] = "予約に失敗しました"
      redirect_to reservations_path
    end
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
    flash[:notice] = "予約情報を削除しました"
    redirect_to reservations_path
  end
  
  private
  
  def reservation_params
    params.require(:reservation).permit(:user_id, :room_id, :check_in, :check_out, :people)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  
  def index
    @rooms = Room.all
  end
  
  def new
    @user = current_user
    @room = Room.new
  end
  
  def create
    @user = current_user
    @room = Room.new(room_params)
    if @room.save
      flash[:notice] = "施設登録が完了しました"
      redirect_to rooms_own_path
    else
      render "rooms/new"
    end
  end
  
  def show
    @room = Room.find(params[:id])
    @reservation = Reservation.new
  end
  
  def edit
    @user = current_user
    @room = Room.find(params[:id])
  end
  
  def update
    @user = current_user
    @room = Room.find(params[:id])
    if @room.update(room_params)
      flash[:notice] = "施設情報を変更しました"
      redirect_to rooms_own_path
    else
      render "edit"
    end
  end
  
  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    flash[:notice] = "施設情報を削除しました"
    redirect_to root_path
  end
  
  def own
    @rooms = Room.where(user_id: current_user.id)
  end

  def search
    @rooms = Room.all
    @keyword = params[:keyword]
    if params[:target] == "area"
      @rooms = Room.where('address LIKE(?)', "%#{@keyword}%")
    else
      @rooms = Room.where(['name LIKE(?) OR introduction LIKE(?)',"%#{@keyword}%","%#{@keyword}%"])
    end
  end
  
  private
  
  def room_params
    params.require(:room).permit(:name, :introduction, :price, :address, :user_id, :image)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
  end
  
  def profile
  end
  
  def edit
    @user = User.find(current_user.id)
  end
  
  def update
    @user = User.find(current_user.id)
    if @user.update(user_params)
      flash[:notice] = "プロフィール情報を変更しました"
      redirect_to users_profile_path
    else
      render "edit"
    end
  end
    
  private
  def user_params
    params.require(:user).permit(:avatar, :name, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="image-wrap">
  <div class="home-content">
    <h1 class="text-center text-light">
      Potepan Shareで<br />
      まだ体験したことのない<br />
      旅をしよう
    </h1>

    <div class="top-search-form my-5">
      <%= form_with url: search_rooms_path, method: :post do |f| %>
        <%= f.text_field :keyword, placeholder: "エリアを検索" %>
        <%= f.hidden_field :target, value: "area" %>
        <%= f.submit"検索" %>
      <% end %>
    </div>
  </div>
</div>

<div class="home-second my-3">
  <h2>おすすめエリア</h2>
  <div class="d-flex justify-content-around">
    <div class="top-search-image">
      <%= form_with url: search_rooms_path, method: :post do |f| %>
        <%= f.hidden_field :keyword, value: "東京都" %>
        <%= f.hidden_field :target, value: "area" %>
        <%= image_submit_tag("tokyo.jpg", class: "area-search tokyo") %>
      <% end %>
      <p>東京/Tokyo</p>
    </div>
    <div class="top-search-image">
      <%= form_with url: search_rooms_path, method: :post do |f| %>
        <%= f.hidden_field :keyword, value: "大阪府" %>
        <%= f.hidden_field :target, value: "area" %>
        <%= image_submit_tag("osaka.jpg", class: "area-search osaka") %>
      <% end %>
      <p>大阪/Osaka</p>
    </div>
    <div class="top-search-image">
      <%= form_with url: search_rooms_path, method: :post do |f| %>
        <%= f.hidden_field :keyword, value: "京都府" %>
        <%= f.hidden_field :target, value: "area" %>
        <%= image_submit_tag("kyoto.jpg", class: "area-search kyoto") %>
      <% end %>
      <p>京都/Kyoto</p>
    </div>
    <div class="top-search-image">
      <%= form_with url: search_rooms_path, method: :post do |f| %>
        <%= f.hidden_field :keyword, value: "札幌市" %>
        <%= f.hidden_field :target, value: "area" %>
        <%= image_submit_tag("sapporo.jpg", class: "area-search kyoto") %>
      <% end %>
      <p>札幌/Sapporo</p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TravelApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </head>

  <body>
    <header class="d-flex justify-content-between align-items-center px-4 bg-secondary">
      <%= link_to"Potepan Share", root_path, class: "h2 text-light" %>
      <% if user_signed_in? %>
        <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
            <% if current_user.avatar.attached? %>
              <%= image_tag current_user.avatar, class:"avatar" %>
            <% else %>
              <%= image_tag('default-avatar.png', class: "img-circle avatar") %>
            <% end %>
            <%= current_user.name %>
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenu1">
            <%= link_to "施設の新規登録", new_room_path, class: "dropdown-item" %>
            <%= link_to "予約済み一覧", reservations_path, class: "dropdown-item" %>
            <%= link_to "登録済み一覧", rooms_own_path, class: "dropdown-item" %>
            <%= link_to "アカウント情報", users_path, class: "dropdown-item" %>
            <%= button_to 'ログアウト', destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            
          </div>
        </div>
      <% else %>
        <div>
          <%= link_to"ログイン", new_user_session_path, class: "btn btn-secondary" %>
          <%= link_to"新規登録", new_user_registration_path, class: "btn btn-primary" %>
        </div>
      <% end %>
    </header>

    <% unless notice == nil && alert == nil%>
      <div class="bg-light w-100 text-center">
        <p class="notice text-info"><%= notice %></p>
        <p class="alert text-danger"><%= alert %></p>
      </div>
    <% end %>

    <div class="container">
      <%= yield %>
    </div>

    <footer class="bg-secondary mt-auto py-2 text-center">
    <p class="text-light">Potepan Share</p>
    </footer>
  </body>
</html>

app/views/reservations/confirm.html.erb
<h3>予約内容の確認</h3>

<table class="center-block" >
  <tr>
    <th>チェックイン</th>
    <td><%= @reservation.check_in.strftime('%Y/%m/%d') %></td>
  </tr>
  <tr>
    <th>チェックアウト</th>
    <td><%= @reservation.check_out.strftime('%Y/%m/%d') %></td>
  </tr>
  <tr>
    <th>日数</th>
    <td>
      <% stay_days = (@reservation.check_out - @reservation.check_in).to_i %>
      <%= stay_days %>日
    </td>
  </tr>
  <tr>
    <th>人数</th>
    <td><%= @reservation.people %>人</td>
  </tr>
   <tr>
    <th>合計金額</th>
    <td>¥<%= (@reservation.room.price * @reservation.people.to_i * stay_days ).to_s(:delimited) %></td>
  </tr>
  <tr>
    <td colspan="2"><p>上記内容で正しければ「確定」ボタンを押してください。</p><td>
  </tr>
  <tr>
    <td colspan="2">
      <%= form_with model: @reservation do |f| %>
        <%= f.hidden_field :user_id %>
        <%= f.hidden_field :room_id %>
        <%= f.hidden_field :check_in %>
        <%= f.hidden_field :check_out %>
        <%= f.hidden_field :people %>
        <%= f.submit "確定する", class: "btn btn-primary w-100" %>
      <% end %>
    </td>
  </tr>
  <tr>
    <td colspan="2"><%= link_to"キャンセル", 'javascript:history.back()', class: "btn btn-secondary w-100" %></td>
  </tr>
</table>

app/views/reservations/index.html.erb
<h3>予約一覧</h3>
<table class="w-100">
  <thead>
    <tr>
      <th>画像</th>
      <th>施設名</th>
      <th>紹介文</th>
      <th>合計金額</th>
      <th>チェックイン</th>
      <th>チェックアウト</th>
      <th>予約確定日時</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td>
          <% if reservation.room.image.attached? %>
            <%= image_tag reservation.room.image, class: "table-image" %>
          <% else %>
            <%= image_tag 'default-image.png', class:"table-image" %>
          <% end %>
        </td>
        <td><%= link_to"#{reservation.room.name}", room_path(reservation.room_id) %></td>
        <td><%= reservation.room.introduction.truncate(30) %></td>
        <td>
          <% stay_days = (reservation.check_out - reservation.check_in).to_i %>
          <p>¥<%= (reservation.room.price * reservation.people * stay_days).to_s(:delimited) %></p>
        </td>
        <td><%= reservation.check_in.strftime("%Y/%m/%d") %></td>
        <td><%= reservation.check_out.strftime("%Y/%m/%d") %></td>
        <td><%= reservation.updated_at.strftime("%Y/%m/%d %H:%M") %></td>
        <td><%= button_to"削除", reservation, method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/rooms/edit.html.erb
<h3>施設情報編集</h3>

<%= render "shared/error", obj: @room %>

<%= form_with model:@room do |f| %>
  <div>
    <%= f.label :name, "施設名" %>
    <%= f.text_field :name, :placeholder => "ルーム名を入力" %>
  </div>

  <div>
    <%= f.label :introduction, "施設詳細" %>
	<%= f.text_area :introduction, :placeholder => "施設詳細を入力" %>
  </div>

  <div>
	<%= f.label :price, "料金" %>
	<%= f.text_field :price, :placeholder => "一日あたりの料金を入力" %>
  </div>

  <div>
    <%= f.label :address, "住所" %>
	<%= f.text_field :address, :placeholder => "住所を入力" %>
  </div>
  
  <div>
	<%= f.label :image, "施設画像" %>
	<%= f.file_field :image %>
  </div>

  <%= f.hidden_field :user_id, value: @user.id %>

  <div>
	<%= f.submit "保存" %>
  </div>
<% end %>

<%= link_to"前のページへ戻る", 'javascript:history.back()' %>

app/views/rooms/index.html.erb
<h3>施設一覧</h3>
<table>
  <tr>
    <th>施設名</th>
    <th>施設紹介</th>
    <th>料金</th>
    <th>住所</th>
    <th>画像</th>
    <th>詳細</th>
  </tr>
  <% @rooms.each do |room| %>
    <tr>
      <td><%= room.name %></td>
      <td><%= room.introduction %></td>
      <td><%= room.price %></td>
      <td><%= room.address %></td>
      <td>
        <% if room.image.attached? %>
          <%= image_tag room.image %>
        <% else %>
          <%= image_tag 'default-image.png' %>
        <% end %>
      </td>
      <td><%= link_to"詳細", room %></td>
    </tr>
  <% end %>
</table>

app/views/rooms/new.html.erb
<h3>施設の新規登録</h3>

<%= render "shared/error", obj: @room %>

<%= form_with model:@room do |f| %>
  <div>
    <table>
      <tr>
        <th><%= f.label :name, "施設名" %></th>
        <td><%= f.text_field :name, :placeholder => "ルーム名を入力" %></td>
      </tr>

      <tr>
        <th><%= f.label :introduction, "施設詳細" %></th>
        <td><%= f.text_area :introduction, :placeholder => "施設詳細を入力" %></td>
      </tr>

      <tr>
        <th><%= f.label :price, "料金" %></th>
        <td><%= f.text_field :price, :placeholder => "一日あたりの料金を入力" %></td>
      </tr>

      <tr>
        <th><%= f.label :address, "住所" %></th>
        <td><%= f.text_field :address, :placeholder => "住所を入力" %></td>
      </tr>
      
      <tr>
        <th><%= f.label :image, "施設画像" %></th>
        <td><%= f.file_field :image %></td>
      </tr>

      <%= f.hidden_field :user_id, value: @user.id %>

      <tr>
        <td colspan="2">
          <%= f.submit "保存", class: "btn btn-primary w-100" %>
        </td>
      </tr>

      <tr>
        <td colspan="2">
          <%= link_to"前のページへ戻る", 'javascript:history.back()', class: "btn btn-secondary w-100" %>
        </td>
      </tr>
    </table>
  </div>
<% end %>

app/views/rooms/own.html.erb
<h3>登録済み一覧</h3>
<table class="w-100">
  <thead>
    <tr>
      <th>画像</th>
      <th>施設名</th>
      <th>紹介文</th>
      <th>料金</th>
      <th>作成日</th>
    </tr>
  </thead>
  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td>
          <% if room.image.attached? %>
            <%= image_tag room.image, class: "table-image" %>
          <% else %>
            <%= image_tag 'default-image.png', class:"table-image" %>
          <% end %>
        </td>
        <td><%= link_to "#{room.name}", room, class: "h4" %></td>
        <td><%= room.introduction.truncate(30) %></td>
        <td>￥<%= room.price.to_s(:delimited) %></td>
        <td><%= room.created_at.strftime("%Y/%m/%d %H:%M") %></td>
        <td><%= button_to"削除", room, method: :delete, data: { confirm: '本当に削除しますか？' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/rooms/search.html.erb
<%= render "shared/search_form" %>

<h3>検索結果</h3>
<p>件数：<%= @rooms.count %>件</p>
<div class="room-grid">
<% @rooms.each do |room| %>
  <div class="room-grid-item bg-light">
    <% if room.image.attached? %>
      <%= image_tag room.image, class: "grid-image" %>
    <% else %>
      <%= image_tag 'default-image.png', class:"grid-image" %>
    <% end %>
    <p class="h4"><%= room.name %></p>
    <p class="text-secondary"><%= room.address %></p>
    <%= room.introduction.truncate(30) %>
    <p>¥<%= room.price.to_s(:delimited) %></p>
    <%= link_to"詳細はこちら", room, class: "btn btn-primary w-100 py-3" %>
  </div>
<% end %>
</div>

app/views/rooms/show.html.erb
<%= render "shared/search_form" %>

<div class="d-flex justify-content-between">
  <%= link_to"戻る", 'javascript:history.back()', class: "h4" %>
  <%if  user_signed_in? %>
    <% if current_user.id == @room.user_id %>
      <%= link_to"編集", [:edit, @room], class: "h4" %>
    <% end %>
  <% end %>
</div>
<div class="d-flex">
  <div>
    <% if @room.image.attached? %>
      <%= image_tag @room.image %>
    <% else %>
      <%= image_tag 'default-image.png' %>
    <% end %>
  </div>
  <div>
    <p class="h3"><%= @room.name %></p>
    <p class="text-secondary"><%= @room.address %></p>
    <p>¥<%= @room.price.to_s(:delimited) %></p>
    <%= @room.introduction %>
  </div>
</div>

<div class="bg-light">
  <table>
    <%= form_with model: @reservation, url: reservations_confirm_path , method: :post do |f| %>
      <tr>
        <th class="h3">予約する</th>
      </tr>
      <tr>
        <th><%= f.label :check_in,"チェックイン" %></th>
        <td><%= f.date_field :check_in%></td>
        <td>
          <% if @reservation.errors.include?(:check_in) %>
            <p style="color: red;"><%= @reservation.errors.full_messages_for(:check_in).first %>
          <% end %>
        </td>
      </tr>
      <tr>
        <th><%= f.label :check_out, "チェックアウト" %></th>
        <td><%= f.date_field :check_out %></td>
        <td>
          <% if @reservation.errors.include?(:check_out) %>
            <p style="color: red;"><%= @reservation.errors.full_messages_for(:check_out).first %>
          <% end %>
        </td>
      </tr>
      <tr>
        <th><%= f.label :people, "人数" %></th>
        <td><%= f.number_field :people %></td>
        <td>
          <% if @reservation.errors.include?(:people) %>
            <p style="color: red;"><%= @reservation.errors.full_messages_for(:people).first %>
          <% end %>
        </td>
      </tr>
      <%= f.hidden_field :room_id, value: @room.id %>
      <tr>
        <td colspan="2">
          <% if user_signed_in? %>
            <%= f.hidden_field :user_id, value: current_user.id %>
            <%= f.submit "予約する", class: "btn btn-primary w-100" %>
          <% else %>
            <%= link_to"ログイン", new_user_session_path, class: "btn btn-primary w-100" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
  <% obj.errors.full_messages.each do |message| %>
    <ul>
      <li><%= message %></li>
    </ul>
  <% end %>
<% end %>

app/views/shared/_search_form.html.erb
<div class="top-search-form d-flex my-5">
  <div class="mr-5">
    <%= form_with url: search_rooms_path, method: :post do |f| %>
      <%= f.text_field :keyword, placeholder: "エリアを検索" %>
      <%= f.hidden_field :target, value: "area" %>
      <%= f.submit"検索" %>
    <% end %>
  </div>
  <div>
    <%= form_with url: search_rooms_path, method: :post do |f| %>
      <%= f.text_field :keyword, placeholder: "キーワード検索" %>
      <%= f.hidden_field :target, value: "keyword" %>
      <%= f.submit"検索" %>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<%= render "shared/error", obj: @user %>

<%= form_for @user do |f| %>
  <div class="field" >
    <%= f.label :avatar, "プロフィール画像" %><br />
    <%= f.file_field :avatar %>
  </div>

  <div class="field">
    <%= f.label :name, "名前" %><br />
    <%= f.text_field :name, autofocus: true, autocomplete: "name" %>
  </div>

  <div class="field">
    <%= f.label :introduction, "自己紹介" %><br />
    <%= f.text_area :introduction %>
  </div>

  <div class="actions">
    <%= f.submit"更新", class: "btn btn-primary" %>
  </div>

  <%= link_to"キャンセル", :back, class: "btn btn-secondary" %>
<% end %>

app/views/users/index.html.erb
<h3>設定</h3>

<div>
  <%= link_to"アカウント", users_path %>
  <%= link_to"プロフィール", users_profile_path %>
</div>

<div>
	<table class="w-100 mt-4 table">
		<tr>
			<th class="h3">アカウント</th>
			<td>
				<%= link_to"編集", edit_user_registration_path %>
			</td>
		</tr>
		<tr>
			<th>メールアドレス</th>
			<td>
				<%= current_user.email %>
			</td>
		</tr>
		<tr>
			<th>パスワード</th>
			<td>*********</td>
		</tr>
	</table>
</div>

app/views/users/show.html.erb
<h3>設定</h3>

<div class="">
  <%= link_to"アカウント", users_path %>
  <%= link_to"プロフィール", users_profile_path %>
</div>

<table class="w-100 mt-4 table">
  <tr>
    <th class="h3">プロフィール</th>
    <td>
		  <%= link_to"編集", edit_user_path %>
    </td>
  </tr>
  <tr>
    <th>アイコン画像</th>
    <td>
    	<% if current_user.avatar.attached? %>
    		<%= image_tag current_user.avatar, class: "avatar" %>
      <% else %>
        <%= image_tag('default-avatar.png', class: "img-circle") %>
      <% end %>
    </td>
  </tr>
  <tr>
    <th>名前</th>
    <td>
      <%= current_user.name %>
    </td>
  </tr>
  <tr>
    <th>自己紹介</th>
    <td>
      <%= current_user.introduction %>
    </td>
  </tr>
</table>